name: GPDS examen practico

on:
  push:
    branches:
      - main
      - 'sprint-*'
  pull_request:
    branches:
      - main
      - 'sprint-*'

jobs:
  ci/cd:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.12.5]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar pruebas automatizadas
      run: |
        pytest tests/ -v --cov=src --cov-report=xml:coverage.xml
    
    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

    - name: Lint Backend
    run: |
      flake8 src/
